#!/bin/bash

#
# This script installs the latest versions of some fine GNOME themes into the current user's ".themes" folder.
#
# Get the most recent version of this script at:
#
#     https://github.com/tliron/install-gnome-themes
#
# Copyright 2016-2020 by Tal Liron. MIT-style license:
#
#     https://github.com/tliron/install-gnome-themes/blob/master/LICENSE
#

set -e

#
# By default the build output is send to: ~/.themes/.install-gnome-themes.conf
#
# You can change this using the LOG environment variable, including setting it to stdout:
#
# 	LOG=/dev/stdout ./install-gnome-themes
#

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
THEMES=~/.themes
LOG=${LOG:-$THEMES/.install-gnome-themes.log}
CONFIG_FILE=${CONFIG_FILE:-$THEMES/.install-gnome-themes.conf}
WORK=/tmp/install-gnome-themes

mkdir --parents "$THEMES"

if [ -f "$LOG" ]; then
	rm "$LOG"
fi

. "$HERE/utils.sh"

function the-end () {
	local ERR=$?
	if [ "$ERR" == 0 ]; then
		message "install-gnome-themes finished successfully" "$GREEN"
	else
		message "install-gnome-themes failed! err=$ERR" "$RED"
	fi
	exit "$ERR"
}

trap the-end EXIT

function crtl-c () {
	message "install-gnome-themes aborted!" "$RED"
	trap - EXIT
	exit 1
}

trap crtl-c INT

#
# Preparation
#

message 'Paths:'
message "  Log file: $LOG"
message "  Configuration file: $CONFIG_FILE"
message "  Target directory: $THEMES"
message "  Work directory: $WORK"

GNOME_VERSION=$(gnome-version)
GTK_VERSION=$(gtk-version)
OS=$(os-name)

message 'Environment:'

if [ -n "$GNOME_VERSION" ]; then
	message "  GNOME: $GNOME_VERSION"
fi
message "  GTK: $GTK_VERSION"
message "  Operating system: $OS"

#
# Themes
#

# Adapta
# https://github.com/tista500/Adapta
# Requirements: autoconf automake inkscape libgdk-pixbuf2.0-dev libglib2.0-dev librsvg2-dev libsass0 libxml2-utils pkg-config sassc
#
# Supports configurations settings, e.g. a variant with colors red500, red300, bluegrey300, bluegrey500:
#
#	ADAPTA_ARGS='
#		--with-selection_color=#F44336 \ 
#		--with-accent_color=#90A4AE \
#		--with-suggestion_color=#607D8B \
#		--with-destruction_color=#FF5252' \
#	./install-gnome-themes
AUTOGEN_ARGS="--disable-cinnamon --disable-xfce --disable-mate --disable-openbox --enable-chrome-legacy $ADAPTA_ARGS" \
SLOW=true \
theme-autogen-prefix github tista500 Adapta master \
	Adapta \
	Adapta-Eta \
	Adapta-Nokto \
	Adapta-Nokto-Eta

# Adwaita Tweaks
# https://github.com/Jazqa/adwaita-tweaks
theme-mv github Jazqa adwaita-tweaks master Adwaita-tweaks

# Amber
# https://github.com/lassekongo83/amber-theme
theme-mv github lassekongo83 amber-theme master Amber

# Ant
# https://github.com/EliverLara/Ant
theme-mv github EliverLara Ant master Ant

# Aqua
# https://github.com/EliverLara/Aqua
theme-mv github EliverLara Aqua master Aqua

# Arc
# https://github.com/jnsh/arc-theme
# Requirements: autoconf automake pkg-config libgtk-3-dev gtk2-engines-murrine
#
# Supports configurations settings, e.g. a variant with transparency disabled:
#
#	ARC_ARGS='
#		--disable-transparency' \
#	./install-gnome-themes
SLOW=true \
theme-script github jnsh arc-theme master "
meson _build --prefix \"\$PWD\"/_deploy -Dthemes=gtk3,gnome-shell &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/Arc* \"$THEMES\"
" \
	Arc \
	Arc-Dark \
	Arc-Darker \
	Arc-Lighter

# Arc-Flatabulous
# https://github.com/andreisergiu98/arc-flatabulous-theme
# Requirements: autoconf automake pkg-config libgtk-3-dev gtk2-engines-murrine
#
# Supports configurations settings, e.g. a variant with transparency disabled:
#
#	ARC_FLATABULOUS_ARGS='
#		--disable-transparency' \
#	./install-gnome-themes
AUTOGEN_ARGS=$ARC_FLATABULOUS_ARGS \
SLOW=true \
theme-autogen-prefix github andreisergiu98 arc-flatabulous-theme master \
	Arc-Flatabulous \
	Arc-Flatabulous-Dark \
	Arc-Flatabulous-Darker

# Blue-Face
# https://github.com/Vistaus/Blue-Face
theme-mv github Vistaus Blue-Face master Blue-Face

# Breeze
# https://github.com/dirruk1/gnome-breeze
# Requirements: gtk2-engines-pixbuf
theme-cp github dirruk1 gnome-breeze master \
	Breeze-gtk \
	Breeze-dark-gtk

# Candra
# https://github.com/killhellokitty/Candra-Themes-3.20
# Requirements: gnome-themes-standard gtk2-engines-murrine gtk2-engines-pixbuf
theme-cp github killhellokitty Candra-Themes-3.20 master \
	Candra-Theme-3.20 \
	Candra-Theme-3.20-Dark \
	Candra-Theme-3.20-Darker

# Canta
# https://github.com/vinceliuice/Canta-theme
theme-script github vinceliuice Canta-theme master "
./install.sh --dest \"$THEMES\"
" \
	Canta \
	Canta-compact \
	Canta-dark \
	Canta-dark-compact \
	Canta-light \
	Canta-light-compact \
	Canta-blue \
	Canta-blue-compact \
	Canta-blue-dark \
	Canta-blue-dark-compact \
	Canta-blue-light \
	Canta-blue-light-compact \
	Canta-indigo \
	Canta-indigo-compact \
	Canta-indigo-dark \
	Canta-indigo-dark-compact \
	Canta-indigo-light \
	Canta-indigo-light-compact

# Chrome-OS
# https://github.com/Elbullazul/Chrome-OS
theme-mv github Elbullazul Chrome-OS master Chrome-OS

# TODO: move to https://github.com/zagortenay333/gnome_shell_and_cinnamon_themes

# Ciliora-Secunda
# https://github.com/zagortenay333/ciliora-secunda-shell
#theme-cp github zagortenay333 ciliora-secunda-shell master Ciliora-Secunda

# Ciliora-Tertia
# https://github.com/zagortenay333/ciliora-tertia-shell
#theme-cp github zagortenay333 ciliora-tertia-shell master Ciliora-Tertia

# Cloak
# https://github.com/killhellokitty/Cloak-3.22
# Requirements: gnome-themes-standard gtk2-engines-murrine gtk2-engines-pixbuf
theme-cp github killhellokitty Cloak-3.22 master Cloak-3.22

# EvoPop
# https://github.com/solus-cold-storage/evopop-gtk-theme
theme-autogen-destdir github solus-cold-storage evopop-gtk-theme master \
	EvoPop \
	EvoPop-Azure	

# Fresh-Finesse
# https://github.com/Vistaus/Fresh-Finesse
theme-cp github Vistaus Fresh-Finesse master Fresh-Finesse

# Greybird
# https://github.com/shimmerproject/Greybird
# Requirements: autoconf automake libgdk-pixbuf2.0-dev libglib2.0-bin sass
theme-script github shimmerproject Greybird master "
meson _build --prefix \"\$PWD\"/_deploy &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/Greybird* \"$THEMES\"
" \
	Greybird \
	Greybird-accessibility \
	Greybird-bright \
	Greybird-compact \
	Greybird-dark \
	Greybird-dark-accessibility

# Layan
# https://github.com/vinceliuice/Layan-gtk-theme
theme-script github vinceliuice Layan-gtk-theme master "
chmod +x install.sh &&
./install.sh --dest \"$THEMES\"
" \
	Layan \
	Layan-dark \
	Layan-dark-solid \
	Layan-light \
	Layan-light-solid \
	Layan-solid

# macOS-Sierra
# https://github.com/Elbullazul/macOS-Sierra
theme-mv github Elbullazul macOS-Sierra master macOS-Sierra

# Materia (formerly Flat-Plat)
# https://github.com/nana-4/materia-theme
theme-script github nana-4 materia-theme master "
meson _build --prefix \"\$PWD\"/_deploy &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/Materia* \"$THEMES\"
" \
	Materia \
	Materia-compact \
	Materia-dark \
	Materia-dark-compact \
	Materia-light \
	Materia-light-compact

# Materiav2
# https://gitlab.com/Gsbhasin84/materiav2
theme-script gitlab Gsbhasin84 materiav2 master "
./install-user.sh \"$THEMES\"
" \
	materiav2-dark-aqua  \
	materiav2-dark-fluent  \
	materiav2-dark-maia  \
	materiav2-dark-mate  \
	materiav2-dark-orange  \
	materiav2-dark-pocillo  \
	materiav2-dark-purple  \
	materiav2-dark-red  \
	materiav2-light-aqua  \
	materiav2-light-fluent  \
	materiav2-light-maia  \
	materiav2-light-mate  \
	materiav2-light-orange  \
	materiav2-light-pocillo  \
	materiav2-light-purple  \
	materiav2-light-red

# Minwaita
# https://github.com/godlyranchdressing/Minwaita
#
# Supports variants, e.g. choosing the Minwaita variant:
#
#       MINWAITA_VARIANT=Minwaita-OSX \
#       ./install-gnome-themes
MINWAITA_VARIANT=${MINWAITA_VARIANT:-Minwaita}
theme-tarball github godlyranchdressing Minwaita master Compiled.tar.gz "Compiled/$MINWAITA_VARIANT" \
	Minwaita \
	Minwaita-Dark \
	Minwaita-Darker \
	Minwaita-Light-Shell

# Mojave
# https://github.com/vinceliuice/Mojave-gtk-theme
theme-script github vinceliuice Mojave-gtk-theme master "
chmod +x install.sh &&
./install.sh --dest \"$THEMES\"
" \
	Mojave-dark \
	Mojave-dark-alt \
	Mojave-dark-solid \
	Mojave-dark-solid-alt \
	Mojave-light \
	Mojave-light-alt \
	Mojave-light-solid \
	Mojave-light-solid-alt

# Numix
# https://github.com/numixproject/numix-gtk-theme
# Requirements: automake libglib2.0-bin libgdk-pixbuf2.0-dev sass
theme-make github numixproject numix-gtk-theme master Numix

# Numix-Base16-Ocean
# https://gitlab.com/commonacc/numix-base16-ocean
# Requirements: automake libglib2.0-bin libgdk-pixbuf2.0-dev sass
theme-make gitlab commonacc numix-base16-ocean master Numix-Base16-Ocean

# Orchis
# https://github.com/vinceliuice/Orchis-theme
theme-script github vinceliuice Orchis-theme master "
chmod +x install.sh &&
./install-all.sh --dest \"$THEMES\"
" \
	Orchis \
	Orchis-dark \
	Orchis-light \
	Orchis-compact \
	Orchis-dark-compact \
	Orchis-light-compact \
	Orchis-purple \
	Orchis-purple-dark \
	Orchis-purple-light \
	Orchis-purple-compact \
	Orchis-purple-dark-compact \
	Orchis-purple-light-compact \
	Orchis-pink \
	Orchis-pink-dark \
	Orchis-pink-light \
	Orchis-pink-compact \
	Orchis-pink-dark-compact \
	Orchis-pink-light-compact \
	Orchis-red \
	Orchis-red-dark \
	Orchis-red-light \
	Orchis-red-compact \
	Orchis-red-dark-compact \
	Orchis-red-light-compact \
	Orchis-orange \
	Orchis-orange-dark \
	Orchis-orange-light \
	Orchis-orange-compact \
	Orchis-orange-dark-compact \
	Orchis-orange-light-compact \
	Orchis-yellow \
	Orchis-yellow-dark \
	Orchis-yellow-light \
	Orchis-yellow-compact \
	Orchis-yellow-dark-compact \
	Orchis-yellow-light-compact \
	Orchis-green \
	Orchis-green-dark \
	Orchis-green-light \
	Orchis-green-compact \
	Orchis-green-dark-compact \
	Orchis-green-light-compact \
	Orchis-grey \
	Orchis-grey-dark \
	Orchis-grey-light \
	Orchis-grey-compact \
	Orchis-grey-dark-compact \
	Orchis-grey-light-compact

# OSX-Arc-Darker
# https://github.com/rufkeya/OSX-Arc-Darker
# Requirements: gnome-themes-standard gtk2-engines-murrine
theme-mv github rufkeya OSX-Arc-Darker master OSX-Arc-Darker

# Paper
# https://github.com/snwh/paper-gtk-theme
# Requirements: automake automake
theme-autogen-destdir github snwh paper-gtk-theme master Paper

# Plano
# https://github.com/lassekongo83/plano-theme
# Requirements: gtk2-engines-murrine gtk2-engines-pixbuf fonts-roboto
theme-mv github lassekongo83 plano-theme master Plano

# Plata
# https://gitlab.com/tista500/plata-theme
# Requirements: autoconf automake inkscape libgdk-pixbuf2.0-dev libglib2.0-dev librsvg2-dev libsass0 libxml2-utils pkg-config sassc
#
# Supports configurations settings, e.g. a variant with colors red500, red300, bluegrey300, bluegrey500:
#
#	PLATA_ARGS='
#		--with-selection_color=#F44336
#		--with-accent_color=#90A4AE
#		--with-suggestion_color=#607D8B' \
#		--with-destruction_color=#FF5252' \
#	./install-gnome-themes
SLOW=true \
AUTOGEN_ARGS="--disable-cinnamon --disable-xfce --disable-mate --disable-openbox $PLATA_ARGS" \
theme-autogen-prefix gitlab tista500 plata-theme master \
	Plata \
	Plata-Compact \
	Plata-Lumine \
	Plata-Lumine-Compact \
	Plata-Noir \
	Plata-Noir-Compact

# Pocillo
# https://github.com/UbuntuBudgie/pocillo-gtk-theme
theme-script github UbuntuBudgie pocillo-gtk-theme master "
meson _build --prefix \"\$PWD\"/_deploy &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/NewPocillo* \"$THEMES\"
" \
	NewPocillo \
	NewPocillo-dark \
	NewPocillo-dark-slim \
	NewPocillo-light \
	NewPocillo-light-slim \
	NewPocillo-slim     

# Pop
# https://github.com/pop-os/gtk-theme
theme-script github pop-os gtk-theme master "
meson _build --prefix \"\$PWD\"/_deploy &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/Pop* \"$THEMES\"
" \
	Pop \
	Pop-dark

# Qogir
# https://github.com/vinceliuice/Qogir-theme
theme-script github vinceliuice Qogir-theme master "
./install.sh --dest \"$THEMES\"
" \
	Qogir \
	Qogir-dark \
	Qogir-light \
	Qogir-manjaro \
	Qogir-manjaro-dark \
	Qogir-manjaro-light \
	Qogir-manjaro-win \
	Qogir-manjaro-win-dark \
	Qogir-manjaro-win-light \
	Qogir-ubuntu \
	Qogir-ubuntu-dark \
	Qogir-ubuntu-light \
	Qogir-ubuntu-win \
	Qogir-ubuntu-win-dark \
	Qogir-ubuntu-win-light \
	Qogir-win \
	Qogir-win-dark \
	Qogir-win-light

# Typewriter
# https://github.com/logico-dev/typewriter-gtk/
theme-mv-dir github logico-dev typewriter-gtk master Typewriter

# United GNOME
# https://github.com/godlyranchdressing/United-GNOME
#
# Supports variants, e.g. choosing the Manjaro variant:
#
#       UNITED_GNOME_VARIANT=Manjaro \
#       ./install-gnome-themes
UNITED_GNOME_VARIANT=${UNITED_GNOME_VARIANT:-$OS}
theme-script github godlyranchdressing United-GNOME master "
tar xf Compiled.tar.gz &&
cp --recursive \"Compiled/United-$UNITED_GNOME_VARIANT/\"* \"$THEMES/\"
" \
	"United-$UNITED_GNOME_VARIANT" \
	"United-$UNITED_GNOME_VARIANT-Light" \
	"United-$UNITED_GNOME_VARIANT-Darker" \
	"United-$UNITED_GNOME_VARIANT-Dark" 

# Unity7
# https://github.com/B00merang-Project/unity7
theme-mv github B00merang-Project unity7 master Unity7

# Unity8
# https://github.com/B00merang-Project/unity8
theme-mv github B00merang-Project unity8 master Unity8

# Vertex
# BROKEN: https://github.com/horst3180/vertex-theme/issues/227
# https://github.com/horst3180/vertex-theme
# Requirements: autoconf automake pkg-config libgtk-3-dev gtk2-engines-murrine
#theme-autogen-prefix github horst3180 vertex-theme master \
#	Vertex \
#	Vertex-Light \
#	Vertex-Dark

# Vimix
# https://github.com/vinceliuice/vimix-gtk-themes
# Requirements: gtk2-engines-murrine gtk2-engines-pixbuf
theme-execute github vinceliuice vimix-gtk-themes master install.sh \
	vimix \
	vimix-beryl \
	vimix-dark \
	vimix-dark-beryl \
	vimix-dark-doder \
	vimix-dark-laptop \
	vimix-dark-laptop-beryl \
	vimix-dark-laptop-doder \
	vimix-dark-laptop-ruby \
	vimix-dark-ruby \
	vimix-doder \
	vimix-laptop \
	vimix-laptop-beryl \
	vimix-laptop-doder \
	vimix-laptop-ruby \
	vimix-light \
	vimix-light-beryl \
	vimix-light-doder \
	vimix-light-laptop \
	vimix-light-laptop-beryl \
	vimix-light-laptop-doder \
	vimix-light-laptop-ruby \
	vimix-light-ruby \
	vimix-ruby

# https://github.com/B00merang-Project/Windows-3.11
theme-mv github B00merang-Project Windows-3.11 master "Windows 3.11"

# https://github.com/B00merang-Project/Windows-7
theme-mv github B00merang-Project Windows-7 master "Windows 7"

# https://github.com/B00merang-Project/Windows-8.1
theme-mv github B00merang-Project Windows-8.1 master "Windows 8.1"

# https://github.com/B00merang-Project/Windows-8.1-Metro
theme-mv github B00merang-Project Windows-8.1-Metro master "Windows 8.1 Metro"

# https://github.com/B00merang-Project/Windows-10
theme-mv github B00merang-Project Windows-10 master "Windows 10"

# https://github.com/B00merang-Project/Windows-10-Acrylic
theme-mv github B00merang-Project Windows-10-Acrylic master "Windows 10 Acrylic"

# https://github.com/B00merang-Project/Windows-10-Acrylic-Dark
theme-mv github B00merang-Project Windows-10-Acrylic-Dark master "Windows 10 Acrylic Dark"

# https://github.com/B00merang-Project/Windows-10-Dark
theme-mv github B00merang-Project Windows-10-Dark master "Windows 10 Dark"

# https://github.com/B00merang-Project/Windows-95
theme-mv github B00merang-Project Windows-95 master "Windows 95"

# https://github.com/B00merang-Project/Windows-Phone-8.1
theme-mv github B00merang-Project Windows-Phone-8.1 master "Windows Phone 8.1"

# https://github.com/B00merang-Project/Windows-Vista
theme-mv github B00merang-Project Windows-Vista master "Windows Vista"

# https://github.com/B00merang-Project/Windows-XP
theme-cp github B00merang-Project Windows-XP master \
	"Windows XP Embedded" \
	"Windows XP Homestead" \
	"Windows XP Luna" \
	"Windows XP Metallic" \
	"Windows XP Royale" \
	"Windows XP Royale Dark" \
	"Windows XP Zune"

# Xenlism-Minimalism
# https://github.com/xenlism/minimalism
theme-mv-dir github xenlism Minimalism master themes/Xenlism-Minimalism

# Yaru
# https://github.com/ubuntu/yaru
theme-script github ubuntu yaru master "
meson _build --prefix \"\$PWD\"/_deploy &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/Yaru \"$THEMES\" &&
rsync --recursive gnome-shell/theme/Yaru/ \"$THEMES\"/Yaru/gnome-shell
" \
	Yaru

# Zuki
# https://github.com/lassekongo83/zuki-themes
# Requirements: gtk2-engines-murrine gtk2-engines-pixbuf fonts-roboto
theme-script github lassekongo83 zuki-themes master "
meson _build --prefix \"\$PWD\"/_deploy &&
cd _build &&
ninja install &&
cd ../_deploy/share &&
rsync --recursive themes/* \"$THEMES\"
" \
	Zukitre \
	Zukitre-dark \
	Zukitwo \
	Zukitwo-dark \
	Zuki-shell
